"""Add notification mechanism to the database

Revision ID: 100cfe53a84
Revises: 3d2668a96dce
Create Date: 2015-05-11 15:51:04.211519

"""

# revision identifiers, used by Alembic.
revision = '100cfe53a84'
down_revision = '3d2668a96dce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationNotificationRecipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Unicode(length=255), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationNotificationRecipients_created', 'TranslationNotificationRecipients', ['created'], unique=False)
    op.create_index(u'ix_TranslationNotificationRecipients_email', 'TranslationNotificationRecipients', ['email'], unique=True)
    op.create_table('TranslationSubscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_url_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('mechanism', sa.Unicode(length=255), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['TranslationNotificationRecipients.id'], ),
    sa.ForeignKeyConstraint(['translation_url_id'], ['TranslationUrls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationSubscriptions_mechanism', 'TranslationSubscriptions', ['mechanism'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationSubscriptions_mechanism', table_name='TranslationSubscriptions')
    op.drop_table('TranslationSubscriptions')
    op.drop_index(u'ix_TranslationNotificationRecipients_email', table_name='TranslationNotificationRecipients')
    op.drop_index(u'ix_TranslationNotificationRecipients_created', table_name='TranslationNotificationRecipients')
    op.drop_table('TranslationNotificationRecipients')
    ### end Alembic commands ###
