"""Add app_thumb and description

Revision ID: 16ac195d729e
Revises: 3a5a4b6c133
Create Date: 2015-04-01 18:57:02.609557

"""

# revision identifiers, used by Alembic.
revision = '16ac195d729e'
down_revision = '3a5a4b6c133'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('app_thumb', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApps', sa.Column('description', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RepositoryApps', 'description')
    op.drop_column('RepositoryApps', 'app_thumb')
    ### end Alembic commands ###
