"""Add same_tool and tool_id

Revision ID: 16f121110a0f
Revises: 2c58f1b857f1
Create Date: 2015-11-09 12:28:43.019410

"""

# revision identifiers, used by Alembic.
revision = '16f121110a0f'
down_revision = '2c58f1b857f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column('same_tool', sa.Boolean(), nullable=True))
    op.add_column('ActiveTranslationMessages', sa.Column('tool_id', sa.Unicode(length=255), nullable=True))
    op.create_index(u'ix_ActiveTranslationMessages_same_tool', 'ActiveTranslationMessages', ['same_tool'], unique=False)
    op.create_index(u'ix_ActiveTranslationMessages_tool_id', 'ActiveTranslationMessages', ['tool_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_ActiveTranslationMessages_tool_id', table_name='ActiveTranslationMessages')
    op.drop_index(u'ix_ActiveTranslationMessages_same_tool', table_name='ActiveTranslationMessages')
    op.drop_column('ActiveTranslationMessages', 'tool_id')
    op.drop_column('ActiveTranslationMessages', 'same_tool')
    ### end Alembic commands ###
