"""Minor cleanup

Revision ID: 182eb89ec642
Revises: 2614c3bbec2a
Create Date: 2014-11-19 15:09:45.727348

"""

# revision identifiers, used by Alembic.
import base64
import uuid

revision = '182eb89ec642'
down_revision = '2614c3bbec2a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


def upgrade():

    # Generate a PID for those Specs that don't have one.

    connection = op.get_bind()
    ids = connection.execute("SELECT id FROM Specs WHERE pid IS NULL")
    for id, in ids:
        # Generate a not-too-long unique and permanent id.
        uid = base64.urlsafe_b64encode(uuid.uuid4().bytes[0:15])
        connection.execute(text("UPDATE Specs SET pid=:pid WHERE id=:id"), pid=uid, id=id)

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apps', u'spec_url')
    op.alter_column('Specs', 'pid',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Specs', 'pid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.add_column('Apps', sa.Column(u'spec_url', sa.VARCHAR(length=600), nullable=True))
    ### end Alembic commands ###
