"""Add unique fields and link between history and active translations

Revision ID: 19128bb7efe0
Revises: 4280e1ce31d9
Create Date: 2015-03-31 12:55:22.925413

"""

# revision identifiers, used by Alembic.
revision = '19128bb7efe0'
down_revision = '4280e1ce31d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column('history_id', sa.Integer(), nullable=True))
    op.drop_index(u'ix_ActiveTranslationMessages_datetime', table_name='ActiveTranslationMessages')
    try:
        op.drop_constraint(u'ActiveTranslationMessages_ibfk_2', 'ActiveTranslationMessages', type_='foreignkey')
        op.create_foreign_key(None, 'ActiveTranslationMessages', 'TranslationMessageHistory', ['history_id'], ['id'])
        op.drop_column('ActiveTranslationMessages', u'user_id')
        op.drop_column('ActiveTranslationMessages', u'datetime')
    except:
        print "drop_constraint, create_foreign_key and drop_column not supported in sqlite"
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column(u'datetime', sa.DATETIME(), nullable=True))
    op.add_column('ActiveTranslationMessages', sa.Column(u'user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ActiveTranslationMessages', type_='foreignkey')
    op.create_foreign_key(u'ActiveTranslationMessages_ibfk_2', 'ActiveTranslationMessages', u'Users', [u'user_id'], [u'id'])
    op.create_index(u'ix_ActiveTranslationMessages_datetime', 'ActiveTranslationMessages', [u'datetime'], unique=False)
    op.drop_column('ActiveTranslationMessages', 'history_id')
    ### end Alembic commands ###
