"""Add Users table

Revision ID: 1d3b0df7f698
Revises: None
Create Date: 2013-09-16 13:16:21.622369

"""

# revision identifiers, used by Alembic.
revision = '1d3b0df7f698'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Unicode(length=50), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.Column('password', sa.Unicode(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    ### end Alembic commands ###
