"""Create structures to avoid so many values

Revision ID: 254f409b0985
Revises: 4b75b53bdb19
Create Date: 2017-06-20 18:49:44.363563

"""

# revision identifiers, used by Alembic.
revision = '254f409b0985'
down_revision = '4b75b53bdb19'

import hashlib
from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql


metadata = sa.MetaData()
Format = sa.Table("Formats", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("name", sa.Unicode(length=255)),
)
Namespace= sa.Table("Namespaces", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("name", sa.Unicode(length=255)),
)

TranslationKey = sa.Table("TranslationKeys", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("name", sa.Unicode(length=255)),
)

TranslationValue = sa.Table("TranslationValues", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("short_value", sa.Unicode(length=255)),
    sa.Column("hash_value", sa.Unicode(length=255)),
    sa.Column("value", sa.UnicodeText),
)

ToolId = sa.Table("ToolIds", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("tool_id", sa.Unicode(length=255)),
)

TranslationMessageHistory = sa.Table("TranslationMessageHistory", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("key", sa.Unicode(length=255)),
    sa.Column("key_id", sa.Integer()),
    sa.Column("value", sa.UnicodeText),
    sa.Column("value_id", sa.Integer()),
    sa.Column("tool_id", sa.Unicode(length=255)),
    sa.Column("tool_id_id", sa.Integer()),
    sa.Column("fmt", sa.Unicode(length=255)),
    sa.Column("fmt_id", sa.Integer()),
    sa.Column("namespace", sa.Unicode(length=255)),
    sa.Column("namespace_id", sa.Integer()),
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationKeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationKeys_name', 'TranslationKeys', ['name'], unique=True)
    op.create_table('TranslationValues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_value', sa.Unicode(length=255), nullable=True),
    sa.Column('hash_value', sa.Unicode(length=255), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_value', 'short_value')
    )
    op.create_index(u'ix_TranslationValues_hash_value', 'TranslationValues', ['hash_value'], unique=False)
    op.create_index(u'ix_TranslationValues_short_value', 'TranslationValues', ['short_value'], unique=False)
    op.create_table('ToolIds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_ToolIds_tool_id', 'ToolIds', ['tool_id'], unique=True)
    op.create_table('Formats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_Formats_name', 'Formats', ['name'], unique=True)
    op.create_table('Namespaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_Namespaces_name', 'Namespaces', ['name'], unique=True)
    op.add_column(u'TranslationMessageHistory', sa.Column('fmt_id', sa.Integer(), nullable=True))
    op.add_column(u'TranslationMessageHistory', sa.Column('key_id', sa.Integer(), nullable=True))
    op.add_column(u'TranslationMessageHistory', sa.Column('namespace_id', sa.Integer(), nullable=True))
    op.add_column(u'TranslationMessageHistory', sa.Column('tool_id_id', sa.Integer(), nullable=True))
    op.add_column(u'TranslationMessageHistory', sa.Column('value_id', sa.Integer(), nullable=True))
    op.create_index(u'ix_TranslationMessageHistory_fmt_id', 'TranslationMessageHistory', ['fmt_id'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_key_id', 'TranslationMessageHistory', ['key_id'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_namespace_id', 'TranslationMessageHistory', ['namespace_id'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_tool_id_id', 'TranslationMessageHistory', ['tool_id_id'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_value_id', 'TranslationMessageHistory', ['value_id'], unique=False)
    op.create_foreign_key(None, 'TranslationMessageHistory', 'ToolIds', ['tool_id_id'], ['id'])
    op.create_foreign_key(None, 'TranslationMessageHistory', 'Namespaces', ['namespace_id'], ['id'])
    op.create_foreign_key(None, 'TranslationMessageHistory', 'TranslationValues', ['value_id'], ['id'])
    op.create_foreign_key(None, 'TranslationMessageHistory', 'TranslationKeys', ['key_id'], ['id'])
    op.create_foreign_key(None, 'TranslationMessageHistory', 'Formats', ['fmt_id'], ['id'])
    ### end Alembic commands ###

    # TODO
    # stmt = sql.select([TranslationMessageHistory.c.value])

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TranslationMessageHistory', type_='foreignkey')
    op.drop_constraint(None, 'TranslationMessageHistory', type_='foreignkey')
    op.drop_constraint(None, 'TranslationMessageHistory', type_='foreignkey')
    op.drop_constraint(None, 'TranslationMessageHistory', type_='foreignkey')
    op.drop_constraint(None, 'TranslationMessageHistory', type_='foreignkey')
    op.drop_index(u'ix_TranslationMessageHistory_value_id', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_tool_id_id', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_namespace_id', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_key_id', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_fmt_id', table_name='TranslationMessageHistory')
    op.drop_column(u'TranslationMessageHistory', 'value_id')
    op.drop_column(u'TranslationMessageHistory', 'tool_id_id')
    op.drop_column(u'TranslationMessageHistory', 'namespace_id')
    op.drop_column(u'TranslationMessageHistory', 'key_id')
    op.drop_column(u'TranslationMessageHistory', 'fmt_id')
    op.drop_index(u'ix_Namespaces_name', table_name='Namespaces')
    op.drop_table('Namespaces')
    op.drop_index(u'ix_Formats_name', table_name='Formats')
    op.drop_table('Formats')
    op.drop_index(u'ix_ToolIds_tool_id', table_name='ToolIds')
    op.drop_table('ToolIds')
    op.drop_index(u'ix_TranslationValues_short_value', table_name='TranslationValues')
    op.drop_index(u'ix_TranslationValues_hash_value', table_name='TranslationValues')
    op.drop_table('TranslationValues')
    op.drop_index(u'ix_TranslationKeys_name', table_name='TranslationKeys')
    op.drop_table('TranslationKeys')
    ### end Alembic commands ###
