"""Add more info

Revision ID: 2639af76b6d1
Revises: 74932447fbf8
Create Date: 2018-02-19 22:55:52.627273

"""

# revision identifiers, used by Alembic.
revision = '2639af76b6d1'
down_revision = '74932447fbf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryAppCheckUrls', sa.Column('proxy_image_works', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryAppCheckUrls_proxy_image_works'), 'RepositoryAppCheckUrls', ['proxy_image_works'], unique=False)
    op.add_column('RepositoryApps', sa.Column('proxy_image_works', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryApps_proxy_image_works'), 'RepositoryApps', ['proxy_image_works'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoryApps_proxy_image_works'), table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'proxy_image_works')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_proxy_image_works'), table_name='RepositoryAppCheckUrls')
    op.drop_column('RepositoryAppCheckUrls', 'proxy_image_works')
    # ### end Alembic commands ###
