"""Remove FastCache

Revision ID: 271e8b4e3c8d
Revises: 490693c8dfe0
Create Date: 2017-07-20 17:51:45.851541

"""

# revision identifiers, used by Alembic.
revision = '271e8b4e3c8d'
down_revision = '490693c8dfe0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'TranslationFastCaches')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'TranslationFastCaches',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'app_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'translation_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column(u'original_messages', mysql.LONGTEXT(), nullable=True),
    sa.Column(u'datetime', sa.DATETIME(), nullable=True),
    sa.Column(u'app_metadata', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
