"""Add from_developer also to the ActiveMessageTranslation

Revision ID: 2943b8eaa095
Revises: 435d360d3398
Create Date: 2015-05-04 18:59:24.113378

"""

# revision identifiers, used by Alembic.
revision = '2943b8eaa095'
down_revision = '435d360d3398'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column('from_developer', sa.Boolean(), nullable=True))
    op.create_index(u'ix_ActiveTranslationMessages_from_developer', 'ActiveTranslationMessages', ['from_developer'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_ActiveTranslationMessages_from_developer', table_name='ActiveTranslationMessages')
    op.drop_column('ActiveTranslationMessages', 'from_developer')
    ### end Alembic commands ###
