"""Add Active translation users

Revision ID: 2a68ba66c32b
Revises: 4148c3cb14ad
Create Date: 2015-04-27 13:32:26.521250

"""

# revision identifiers, used by Alembic.
revision = '2a68ba66c32b'
down_revision = '4148c3cb14ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationCurrentActiveUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['TranslationBundles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['GoLabOAuthUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationCurrentActiveUsers_last_check', 'TranslationCurrentActiveUsers', ['last_check'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationCurrentActiveUsers_last_check', table_name='TranslationCurrentActiveUsers')
    op.drop_table('TranslationCurrentActiveUsers')
    ### end Alembic commands ###
