"""Add number of apps in sync

Revision ID: 2c58f1b857f1
Revises: 8a6fa691283
Create Date: 2015-11-04 06:24:34.354216

"""

# revision identifiers, used by Alembic.
revision = '2c58f1b857f1'
down_revision = '8a6fa691283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationSyncLogs', sa.Column('number_apps', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TranslationSyncLogs', 'number_apps')
    ### end Alembic commands ###
