"""Added Bundles and Messages tables as well as new relationships

Revision ID: 2d3d6675101a
Revises: 182eb89ec642
Create Date: 2014-11-19 16:54:49.694432

"""

# revision identifiers, used by Alembic.
revision = '2d3d6675101a'
down_revision = '182eb89ec642'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Unicode(length=15), nullable=True),
    sa.Column('target', sa.Unicode(length=30), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['Apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=50), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['Bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Messages')
    op.drop_table('Bundles')
    ### end Alembic commands ###
