"""Add index to url

Revision ID: 2f15229eefbd
Revises: 4167d142d57b
Create Date: 2017-10-14 20:16:16.172385

"""

# revision identifiers, used by Alembic.
revision = '2f15229eefbd'
down_revision = '4167d142d57b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_RepositoryApps_url_shortened', 'RepositoryApps', ['url'], unique=False, mysql_length={'url': 255})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_RepositoryApps_url_shortened', table_name='RepositoryApps')
    # ### end Alembic commands ###
