"""Add taken_from_default field

Revision ID: 2f1bb61ffea
Revises: e220a74734b
Create Date: 2015-04-10 17:45:16.727882

"""

# revision identifiers, used by Alembic.
revision = '2f1bb61ffea'
down_revision = 'e220a74734b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column('taken_from_default', sa.Boolean(), nullable=True))
    op.create_index(u'ix_ActiveTranslationMessages_taken_from_default', 'ActiveTranslationMessages', ['taken_from_default'], unique=False)
    op.add_column('TranslationMessageHistory', sa.Column('taken_from_default', sa.Boolean(), nullable=True))
    op.create_index(u'ix_TranslationMessageHistory_parent_translation_id', 'TranslationMessageHistory', ['parent_translation_id'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_taken_from_default', 'TranslationMessageHistory', ['taken_from_default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationMessageHistory_taken_from_default', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_parent_translation_id', table_name='TranslationMessageHistory')
    op.drop_column('TranslationMessageHistory', 'taken_from_default')
    op.drop_index(u'ix_ActiveTranslationMessages_taken_from_default', table_name='ActiveTranslationMessages')
    op.drop_column('ActiveTranslationMessages', 'taken_from_default')
    ### end Alembic commands ###
