"""Add app.data

Revision ID: 33bc14d712b2
Revises: 50afb8b620ff
Create Date: 2013-09-18 00:42:29.478180

"""

# revision identifiers, used by Alembic.
revision = '33bc14d712b2'
down_revision = '50afb8b620ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('Apps', sa.Column('data', sa.Text(), server_default=u'{}', nullable=False))
    except:
        # In certain environments (such as MySQL), default value is not acceptable
        op.add_column('Apps', sa.Column('data', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apps', 'data')
    ### end Alembic commands ###
