"""Add App

Revision ID: 3466afd5950f
Revises: 1d3b0df7f698
Create Date: 2013-09-17 23:12:36.391127

"""

# revision identifiers, used by Alembic.
revision = '3466afd5950f'
down_revision = '1d3b0df7f698'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.Unicode(length=50), nullable=True),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('modification_date', sa.DateTime(), nullable=False),
    sa.Column('last_access_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name','owner_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Apps')
    ### end Alembic commands ###
