"""Add creation to the external suggestions

Revision ID: 381fdb66ec27
Revises: 3c994ef50934
Create Date: 2017-07-28 13:47:47.103811

"""

# revision identifiers, used by Alembic.
revision = '381fdb66ec27'
down_revision = '3c994ef50934'

import datetime
from alembic import op
from sqlalchemy import DateTime, and_
from sqlalchemy.sql import column, table, select
import sqlalchemy as sa

TranslationExternalSuggestions = table('TranslationExternalSuggestions',
    column('created', DateTime),
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationExternalSuggestions', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###
    stmt = TranslationExternalSuggestions.update().values({ 'created': datetime.datetime.utcnow() })
    op.execute(stmt)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TranslationExternalSuggestions', 'created')
    ### end Alembic commands ###
