"""Remove etag and last-modified from local db

Revision ID: 3a5a4b6c133
Revises: 19128bb7efe0
Create Date: 2015-04-01 18:22:25.713005

"""

# revision identifiers, used by Alembic.
revision = '3a5a4b6c133'
down_revision = '19128bb7efe0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('external_id', sa.Unicode(length=200), nullable=True))
    op.create_index(u'ix_RepositoryApps_external_id', 'RepositoryApps', ['external_id'], unique=False)
    try:
        op.drop_column('RepositoryApps', u'http_etag')
        op.drop_column('RepositoryApps', u'http_last_modified')
    except:
        print "drop column not supported in sqlite"
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column(u'http_last_modified', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('RepositoryApps', sa.Column(u'http_etag', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index(u'ix_RepositoryApps_external_id', table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'external_id')
    ### end Alembic commands ###
