"""Added AppVar table to models

Revision ID: 3a731ce5846e
Revises: 9cb5a6027a6
Create Date: 2013-11-20 15:06:30.761000

"""

# revision identifiers, used by Alembic.
revision = '3a731ce5846e'
down_revision = '9cb5a6027a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppVars',
    sa.Column('var_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=50), nullable=True),
    sa.Column('value', sa.Unicode(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['Apps.id'], ),
    sa.PrimaryKeyConstraint('var_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AppVars')
    ### end Alembic commands ###
