"""Add metadata to FastCache

Revision ID: 3d2668a96dce
Revises: 4e20dff98010
Create Date: 2015-05-11 14:03:10.890043

"""

# revision identifiers, used by Alembic.
revision = '3d2668a96dce'
down_revision = '4e20dff98010'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql

from appcomposer.db import db
from appcomposer.application import app

metadata = db.MetaData()
translation_fast_caches = db.Table('TranslationFastCaches', metadata,
    db.Column('id', db.Integer()),
)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationFastCaches', sa.Column('app_metadata', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###

    with app.app_context():
        delete_stmt = translation_fast_caches.delete()
        db.session.execute(delete_stmt)
        db.session.commit()


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TranslationFastCaches', 'app_metadata')
    ### end Alembic commands ###
