"""Add active

Revision ID: 3efdb537f933
Revises: a3997837668c
Create Date: 2017-10-15 15:44:59.467816

"""

# revision identifiers, used by Alembic.
revision = '3efdb537f933'
down_revision = 'a3997837668c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryAppCheckUrls', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryAppCheckUrls_active'), 'RepositoryAppCheckUrls', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_active'), table_name='RepositoryAppCheckUrls')
    op.drop_column('RepositoryAppCheckUrls', 'active')
    # ### end Alembic commands ###
