"""Add RepositoryApplications to models

Revision ID: 3f1d7cfafe36
Revises: 2d3d6675101a
Create Date: 2014-12-04 12:48:03.328935

"""

# revision identifiers, used by Alembic.
revision = '3f1d7cfafe36'
down_revision = '2d3d6675101a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.Unicode(length=400), nullable=False),
    sa.Column('url', sa.Unicode(length=500), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('adaptable', sa.Boolean(), nullable=True),
    sa.Column('translatable', sa.Boolean(), nullable=True),
    sa.Column('original_translations', sa.Unicode(length=500), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.Column('failing', sa.Boolean(), nullable=True),
    sa.Column('failing_since', sa.DateTime(), nullable=True),
    sa.Column('http_last_modified', sa.Unicode(length=64), nullable=True),
    sa.Column('http_etag', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_app')
    ### end Alembic commands ###
