"""Use long text

Revision ID: 4167d142d57b
Revises: d20615919d80
Create Date: 2017-10-14 20:11:11.896961

"""

# revision identifiers, used by Alembic.
revision = '4167d142d57b'
down_revision = 'd20615919d80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_RepositoryApps_url', table_name='RepositoryApps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_RepositoryApps_url', 'RepositoryApps', ['url'], unique=False)
    # ### end Alembic commands ###
