"""Add description to App

Revision ID: 4211b3736e90
Revises: 542cdf68faa5
Create Date: 2014-05-19 19:13:17.086649

"""

# revision identifiers, used by Alembic.
revision = '4211b3736e90'
down_revision = '542cdf68faa5'

import json
from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql

metadata = sa.MetaData()
app = sa.Table("Apps", metadata,
    sa.Column("id", sa.Integer()),
    sa.Column("data", sa.Text),
    sa.Column("description", sa.Unicode(length=1000)),
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Apps', sa.Column('description', sa.Unicode(length=1000), nullable=True))
    ### end Alembic commands ###

    apps_changes = {}
    apps_data = sql.select([app.c.id, app.c.data])
    for row in op.get_bind().execute(apps_data):
        try:
            contents = json.loads(row[app.c.data])
        except:
            continue

        if 'description' in contents:
            apps_changes[row[app.c.id]] = contents['description']

    for app_id in apps_changes:
        update_stmt = app.update().where(app.c.id == app_id).values(description = apps_changes[app_id])
        op.execute(update_stmt)



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apps', 'description')
    ### end Alembic commands ###
