"""Create new translator tables

Revision ID: 4280e1ce31d9
Revises: 3f1d7cfafe36
Create Date: 2015-03-31 00:20:10.386472

"""

# revision identifiers, used by Alembic.
revision = '4280e1ce31d9'
down_revision = '3f1d7cfafe36'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationUrls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationUrls_url', 'TranslationUrls', ['url'], unique=True)
    op.create_table('TranslationValueSuggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('human_key', sa.Unicode(length=255), nullable=True),
    sa.Column('language', sa.Unicode(length=20), nullable=True),
    sa.Column('target', sa.Unicode(length=20), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationValueSuggestions_human_key', 'TranslationValueSuggestions', ['human_key'], unique=False)
    op.create_index(u'ix_TranslationValueSuggestions_language', 'TranslationValueSuggestions', ['language'], unique=False)
    op.create_index(u'ix_TranslationValueSuggestions_target', 'TranslationValueSuggestions', ['target'], unique=False)
    op.create_table('RepositoryApps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository', sa.Unicode(length=400), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('adaptable', sa.Boolean(), nullable=True),
    sa.Column('translatable', sa.Boolean(), nullable=True),
    sa.Column('original_translations', sa.Unicode(length=255), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.Column('failing', sa.Boolean(), nullable=True),
    sa.Column('failing_since', sa.DateTime(), nullable=True),
    sa.Column('http_last_modified', sa.Unicode(length=64), nullable=True),
    sa.Column('http_etag', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_RepositoryApps_adaptable', 'RepositoryApps', ['adaptable'], unique=False)
    op.create_index(u'ix_RepositoryApps_failing', 'RepositoryApps', ['failing'], unique=False)
    op.create_index(u'ix_RepositoryApps_failing_since', 'RepositoryApps', ['failing_since'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_change', 'RepositoryApps', ['last_change'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_check', 'RepositoryApps', ['last_check'], unique=False)
    op.create_index(u'ix_RepositoryApps_name', 'RepositoryApps', ['name'], unique=False)
    op.create_index(u'ix_RepositoryApps_repository', 'RepositoryApps', ['repository'], unique=False)
    op.create_index(u'ix_RepositoryApps_translatable', 'RepositoryApps', ['translatable'], unique=False)
    op.create_index(u'ix_RepositoryApps_url', 'RepositoryApps', ['url'], unique=True)
    op.create_table('TranslationKeySuggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=255), nullable=True),
    sa.Column('language', sa.Unicode(length=20), nullable=True),
    sa.Column('target', sa.Unicode(length=20), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationKeySuggestions_key', 'TranslationKeySuggestions', ['key'], unique=False)
    op.create_index(u'ix_TranslationKeySuggestions_language', 'TranslationKeySuggestions', ['language'], unique=False)
    op.create_index(u'ix_TranslationKeySuggestions_target', 'TranslationKeySuggestions', ['target'], unique=False)
    op.create_table('TranslatedApps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_url_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.ForeignKeyConstraint(['translation_url_id'], ['TranslationUrls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslatedApps_url', 'TranslatedApps', ['url'], unique=True)
    op.create_table('TranslationBundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_url_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Unicode(length=20), nullable=True),
    sa.Column('target', sa.Unicode(length=20), nullable=True),
    sa.ForeignKeyConstraint(['translation_url_id'], ['TranslationUrls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationBundles_language', 'TranslationBundles', ['language'], unique=False)
    op.create_index(u'ix_TranslationBundles_target', 'TranslationBundles', ['target'], unique=False)
    op.create_table('TranslationMessageHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Unicode(length=255), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('parent_translation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['TranslationBundles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationMessageHistory_datetime', 'TranslationMessageHistory', ['datetime'], unique=False)
    op.create_index(u'ix_TranslationMessageHistory_key', 'TranslationMessageHistory', ['key'], unique=False)
    op.create_table('ActiveTranslationMessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.Unicode(length=255), nullable=True),
    sa.Column('value', sa.UnicodeText(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['TranslationBundles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_ActiveTranslationMessages_datetime', 'ActiveTranslationMessages', ['datetime'], unique=False)
    op.create_index(u'ix_ActiveTranslationMessages_key', 'ActiveTranslationMessages', ['key'], unique=False)
    op.drop_table(u'repository_app')
    op.create_index(u'ix_AppVersions_creation_date', 'AppVersions', ['creation_date'], unique=False)
    op.create_index(u'ix_Apps_composer', 'Apps', ['composer'], unique=False)
    op.create_index(u'ix_Apps_creation_date', 'Apps', ['creation_date'], unique=False)
    op.create_index(u'ix_Apps_last_access_date', 'Apps', ['last_access_date'], unique=False)
    op.create_index(u'ix_Apps_modification_date', 'Apps', ['modification_date'], unique=False)
    op.create_index(u'ix_Apps_name', 'Apps', ['name'], unique=False)
    op.create_index(u'ix_Apps_owner_id', 'Apps', ['owner_id'], unique=False)
    op.create_index(u'ix_Apps_unique_id', 'Apps', ['unique_id'], unique=True)
    try:
        op.create_foreign_key(None, 'Apps', 'Specs', ['spec_id'], ['id'])
    except:
        print "create_foreign_key not supported in sqlite"
    op.create_index(u'ix_Users_creation_date', 'Users', ['creation_date'], unique=False)
    op.create_index(u'ix_Users_last_access_date', 'Users', ['last_access_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_Users_last_access_date', table_name='Users')
    op.drop_index(u'ix_Users_creation_date', table_name='Users')
    op.drop_constraint(None, 'Apps', type_='foreignkey')
    op.drop_index(u'ix_Apps_unique_id', table_name='Apps')
    op.drop_index(u'ix_Apps_owner_id', table_name='Apps')
    op.drop_index(u'ix_Apps_name', table_name='Apps')
    op.drop_index(u'ix_Apps_modification_date', table_name='Apps')
    op.drop_index(u'ix_Apps_last_access_date', table_name='Apps')
    op.drop_index(u'ix_Apps_creation_date', table_name='Apps')
    op.drop_index(u'ix_Apps_composer', table_name='Apps')
    op.drop_index(u'ix_AppVersions_creation_date', table_name='AppVersions')
    op.create_table(u'repository_app',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'repository', mysql.VARCHAR(length=400), nullable=False),
    sa.Column(u'url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column(u'adaptable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column(u'translatable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column(u'original_translations', mysql.VARCHAR(length=500), nullable=True),
    sa.Column(u'last_check', sa.DATETIME(), nullable=True),
    sa.Column(u'last_change', sa.DATETIME(), nullable=True),
    sa.Column(u'failing', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column(u'failing_since', sa.DATETIME(), nullable=True),
    sa.Column(u'http_last_modified', mysql.VARCHAR(length=64), nullable=True),
    sa.Column(u'http_etag', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(u'ix_ActiveTranslationMessages_key', table_name='ActiveTranslationMessages')
    op.drop_index(u'ix_ActiveTranslationMessages_datetime', table_name='ActiveTranslationMessages')
    op.drop_table('ActiveTranslationMessages')
    op.drop_index(u'ix_TranslationMessageHistory_key', table_name='TranslationMessageHistory')
    op.drop_index(u'ix_TranslationMessageHistory_datetime', table_name='TranslationMessageHistory')
    op.drop_table('TranslationMessageHistory')
    op.drop_index(u'ix_TranslationBundles_target', table_name='TranslationBundles')
    op.drop_index(u'ix_TranslationBundles_language', table_name='TranslationBundles')
    op.drop_table('TranslationBundles')
    op.drop_index(u'ix_TranslatedApps_url', table_name='TranslatedApps')
    op.drop_table('TranslatedApps')
    op.drop_index(u'ix_TranslationKeySuggestions_target', table_name='TranslationKeySuggestions')
    op.drop_index(u'ix_TranslationKeySuggestions_language', table_name='TranslationKeySuggestions')
    op.drop_index(u'ix_TranslationKeySuggestions_key', table_name='TranslationKeySuggestions')
    op.drop_table('TranslationKeySuggestions')
    op.drop_index(u'ix_RepositoryApps_url', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_translatable', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_repository', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_name', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_last_check', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_last_change', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_failing_since', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_failing', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_adaptable', table_name='RepositoryApps')
    op.drop_table('RepositoryApps')
    op.drop_index(u'ix_TranslationValueSuggestions_target', table_name='TranslationValueSuggestions')
    op.drop_index(u'ix_TranslationValueSuggestions_language', table_name='TranslationValueSuggestions')
    op.drop_index(u'ix_TranslationValueSuggestions_human_key', table_name='TranslationValueSuggestions')
    op.drop_table('TranslationValueSuggestions')
    op.drop_index(u'ix_TranslationUrls_url', table_name='TranslationUrls')
    op.drop_table('TranslationUrls')
    ### end Alembic commands ###
