"""Add origin_language

Revision ID: 44d704928d8c
Revises: 2ef3688b5383
Create Date: 2015-04-19 13:06:04.716473

"""

# revision identifiers, used by Alembic.
revision = '44d704928d8c'
down_revision = '2ef3688b5383'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationExternalSuggestions', sa.Column('origin_language', sa.Unicode(length=20), nullable=True))
    op.create_index(u'ix_TranslationExternalSuggestions_origin_language', 'TranslationExternalSuggestions', ['origin_language'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationExternalSuggestions_origin_language', table_name='TranslationExternalSuggestions')
    op.drop_column('TranslationExternalSuggestions', 'origin_language')
    ### end Alembic commands ###
