"""Add FastCache for avoiding retrieving the app_url in every single update

Revision ID: 471e6f7722a7
Revises: 6d09f595667
Create Date: 2015-04-14 07:40:57.006143

"""

# revision identifiers, used by Alembic.
revision = '471e6f7722a7'
down_revision = '6d09f595667'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationFastCaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_url', sa.Unicode(length=255), nullable=True),
    sa.Column('translation_url', sa.Unicode(length=255), nullable=True),
    sa.Column('original_messages', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_TranslationFastCaches_app_url', 'TranslationFastCaches', ['app_url'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationFastCaches_app_url', table_name='TranslationFastCaches')
    op.drop_table('TranslationFastCaches')
    ### end Alembic commands ###
