"""Add embed application model

Revision ID: 4811ae4298e3
Revises: 51d493c4d3e1
Create Date: 2015-07-31 15:01:02.135850

"""

# revision identifiers, used by Alembic.
revision = '4811ae4298e3'
down_revision = '51d493c4d3e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmbedApplications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.Unicode(length=36), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['GoLabOAuthUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplications_creation', 'EmbedApplications', ['creation'], unique=False)
    op.create_index(u'ix_EmbedApplications_identifier', 'EmbedApplications', ['identifier'], unique=True)
    op.create_index(u'ix_EmbedApplications_last_update', 'EmbedApplications', ['last_update'], unique=False)
    op.create_index(u'ix_EmbedApplications_name', 'EmbedApplications', ['name'], unique=False)
    op.create_index(u'ix_EmbedApplications_url', 'EmbedApplications', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_EmbedApplications_url', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_name', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_last_update', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_identifier', table_name='EmbedApplications')
    op.drop_index(u'ix_EmbedApplications_creation', table_name='EmbedApplications')
    op.drop_table('EmbedApplications')
    ### end Alembic commands ###
