"""Add metadata for faster downloads

Revision ID: 490693c8dfe0
Revises: 4b75b53bdb19
Create Date: 2017-07-19 16:48:32.029613

"""

# revision identifiers, used by Alembic.
revision = '490693c8dfe0'
down_revision = '4b75b53bdb19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApp2languages', sa.Column('downloaded_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApp2languages', sa.Column('error', sa.Boolean(), nullable=True))
    op.add_column('RepositoryApp2languages', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('RepositoryApp2languages', sa.Column('last_processed_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApp2languages', sa.Column('last_processed_time', sa.DateTime(), nullable=True))
    op.create_index(u'ix_RepositoryApp2languages_downloaded_hash', 'RepositoryApp2languages', ['downloaded_hash'], unique=False)
    op.create_index(u'ix_RepositoryApp2languages_error', 'RepositoryApp2languages', ['error'], unique=False)
    op.create_index(u'ix_RepositoryApp2languages_last_processed_hash', 'RepositoryApp2languages', ['last_processed_hash'], unique=False)
    op.create_index(u'ix_RepositoryApp2languages_last_processed_time', 'RepositoryApp2languages', ['last_processed_time'], unique=False)
    op.add_column('RepositoryApps', sa.Column('downloaded_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApps', sa.Column('last_processed_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApps', sa.Column('last_processed_time', sa.DateTime(), nullable=True))
    op.create_index(u'ix_RepositoryApps_downloaded_hash', 'RepositoryApps', ['downloaded_hash'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_processed_hash', 'RepositoryApps', ['last_processed_hash'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_processed_time', 'RepositoryApps', ['last_processed_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_RepositoryApps_last_processed_time', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_last_processed_hash', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_downloaded_hash', table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'last_processed_time')
    op.drop_column('RepositoryApps', 'last_processed_hash')
    op.drop_column('RepositoryApps', 'downloaded_hash')
    op.drop_index(u'ix_RepositoryApp2languages_last_processed_time', table_name='RepositoryApp2languages')
    op.drop_index(u'ix_RepositoryApp2languages_last_processed_hash', table_name='RepositoryApp2languages')
    op.drop_index(u'ix_RepositoryApp2languages_error', table_name='RepositoryApp2languages')
    op.drop_index(u'ix_RepositoryApp2languages_downloaded_hash', table_name='RepositoryApp2languages')
    op.drop_column('RepositoryApp2languages', 'last_processed_time')
    op.drop_column('RepositoryApp2languages', 'last_processed_hash')
    op.drop_column('RepositoryApp2languages', 'id')
    op.drop_column('RepositoryApp2languages', 'error')
    op.drop_column('RepositoryApp2languages', 'downloaded_hash')
    ### end Alembic commands ###
