"""Remove original_translations

Revision ID: 4b75b53bdb19
Revises: bc497a3d230
Create Date: 2017-06-15 21:39:36.378271

"""

# revision identifiers, used by Alembic.
revision = '4b75b53bdb19'
down_revision = 'bc497a3d230'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_Languages_language', 'Languages', ['language'], unique=True)
    op.create_table('RepositoryApp2languages',
    sa.Column('repository_app_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['Languages.id'], ),
    sa.ForeignKeyConstraint(['repository_app_id'], ['RepositoryApps.id'], )
    )
    op.drop_column(u'RepositoryApps', u'original_translations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'RepositoryApps', sa.Column(u'original_translations', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('RepositoryApp2languages')
    op.drop_index(u'ix_Languages_language', table_name='Languages')
    op.drop_table('Languages')
    ### end Alembic commands ###
