"""Add namespace to ActiveTranslation

Revision ID: 4c0992d0b552
Revises: 2943b8eaa095
Create Date: 2015-05-07 18:25:09.526231

"""

# revision identifiers, used by Alembic.
revision = '4c0992d0b552'
down_revision = '2943b8eaa095'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ActiveTranslationMessages', sa.Column('namespace', sa.Unicode(length=255), nullable=True))
    op.create_index(u'ix_ActiveTranslationMessages_namespace', 'ActiveTranslationMessages', ['namespace'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_ActiveTranslationMessages_namespace', table_name='ActiveTranslationMessages')
    op.drop_column('ActiveTranslationMessages', 'namespace')
    ### end Alembic commands ###
