"""Add attributes to the TranslationUrl model

Revision ID: 4db77f01caa4
Revises: 33dbbabeba2b
Create Date: 2015-11-27 10:34:45.500892

"""

# revision identifiers, used by Alembic.
revision = '4db77f01caa4'
down_revision = '33dbbabeba2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationUrls', sa.Column('attribs', sa.UnicodeText(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TranslationUrls', 'attribs')
    ### end Alembic commands ###
