"""Add automatic to TranslationUrl

Revision ID: 4e20dff98010
Revises: 4c0992d0b552
Create Date: 2015-05-11 11:29:49.824142

"""

# revision identifiers, used by Alembic.
revision = '4e20dff98010'
down_revision = '4c0992d0b552'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.sql as sql

from appcomposer.db import db
from appcomposer.application import app

metadata = db.MetaData()
translation_urls = db.Table('TranslationUrls', metadata,
    db.Column('id', db.Integer()),
    db.Column('automatic', db.Boolean),
)

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationUrls', sa.Column('automatic', sa.Boolean(), nullable=True))
    op.create_index(u'ix_TranslationUrls_automatic', 'TranslationUrls', ['automatic'], unique=False)
    ### end Alembic commands ###

    with app.app_context():
        update_stmt = translation_urls.update().values(automatic = True)
        db.session.execute(update_stmt)
        db.session.commit()

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_TranslationUrls_automatic', table_name='TranslationUrls')
    op.drop_column('TranslationUrls', 'automatic')
    ### end Alembic commands ###
