"""[Users]: Was missing --autogenerate, so cols weren't added properly

Revision ID: 501404b36cef
Revises: 4f503b0ca8db
Create Date: 2013-09-20 16:01:24.895000

"""

# revision identifiers, used by Alembic.
revision = '501404b36cef'
down_revision = '4f503b0ca8db'

from alembic import op
import sqlalchemy as sa
import datetime

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('creation_date', sa.DateTime(), nullable=False, server_default=datetime.datetime.now().__str__()))
    op.add_column('Users', sa.Column('email', sa.Unicode(length=254), nullable=False, server_default="no-reply@default.com"))
    op.add_column('Users', sa.Column('last_access_date', sa.DateTime(), nullable=False, server_default=datetime.datetime.now().__str__()))
    op.add_column('Users', sa.Column('organization', sa.Unicode(length=50), nullable=True))
    op.add_column('Users', sa.Column('role', sa.Unicode(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():    pass    # SQLITE doesn't support ALTER TABLE DROP
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('Users', 'role')
    # op.drop_column('Users', 'organization')
    # op.drop_column('Users', 'last_access_date')
    # op.drop_column('Users', 'email')
    # op.drop_column('Users', 'creation_date')
    ### end Alembic commands ###
