"""Add contents_hash

Revision ID: 515f518eff57
Revises: 218fd78e07e8
Create Date: 2017-07-25 15:21:18.613141

"""

# revision identifiers, used by Alembic.
revision = '515f518eff57'
down_revision = '218fd78e07e8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('contents_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApps', sa.Column('last_processed_contents_hash', sa.Unicode(length=255), nullable=True))
    op.add_column('RepositoryApps', sa.Column('last_processed_downloaded_hash', sa.Unicode(length=255), nullable=True))
    op.create_index(u'ix_RepositoryApps_contents_hash', 'RepositoryApps', ['contents_hash'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_processed_contents_hash', 'RepositoryApps', ['last_processed_contents_hash'], unique=False)
    op.create_index(u'ix_RepositoryApps_last_processed_downloaded_hash', 'RepositoryApps', ['last_processed_downloaded_hash'], unique=False)
    op.drop_index(u'ix_RepositoryApps_last_processed_hash', table_name='RepositoryApps')
    op.drop_column('RepositoryApps', u'last_processed_hash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column(u'last_processed_hash', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(u'ix_RepositoryApps_last_processed_hash', 'RepositoryApps', [u'last_processed_hash'], unique=False)
    op.drop_index(u'ix_RepositoryApps_last_processed_downloaded_hash', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_last_processed_contents_hash', table_name='RepositoryApps')
    op.drop_index(u'ix_RepositoryApps_contents_hash', table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'last_processed_downloaded_hash')
    op.drop_column('RepositoryApps', 'last_processed_contents_hash')
    op.drop_column('RepositoryApps', 'contents_hash')
    ### end Alembic commands ###
