"""Add uses_proxy

Revision ID: 72dd4cdad196
Revises: af0f4b8caa2a
Create Date: 2019-02-20 18:56:52.422214

"""

# revision identifiers, used by Alembic.
revision = '72dd4cdad196'
down_revision = 'af0f4b8caa2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('uses_proxy', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryApps_uses_proxy'), 'RepositoryApps', ['uses_proxy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoryApps_uses_proxy'), table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'uses_proxy')
    # ### end Alembic commands ###
