"""Make preview_link nullable

Revision ID: 74932447fbf8
Revises: a3fbffab4a7d
Create Date: 2018-01-15 01:36:47.803008

"""

# revision identifiers, used by Alembic.
revision = '74932447fbf8'
down_revision = 'a3fbffab4a7d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RepositoryApps', 'preview_link',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RepositoryApps', 'preview_link',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
