"""Add proxy_image_stored

Revision ID: 7fb89edaa44d
Revises: 2639af76b6d1
Create Date: 2018-02-19 23:27:24.310094

"""

# revision identifiers, used by Alembic.
revision = '7fb89edaa44d'
down_revision = '2639af76b6d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryAppCheckUrls', sa.Column('proxy_image_stored', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryAppCheckUrls_proxy_image_stored'), 'RepositoryAppCheckUrls', ['proxy_image_stored'], unique=False)
    op.add_column('RepositoryApps', sa.Column('proxy_image_stored', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryApps_proxy_image_stored'), 'RepositoryApps', ['proxy_image_stored'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoryApps_proxy_image_stored'), table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'proxy_image_stored')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_proxy_image_stored'), table_name='RepositoryAppCheckUrls')
    op.drop_column('RepositoryAppCheckUrls', 'proxy_image_stored')
    # ### end Alembic commands ###
