"""Add tags to synclog

Revision ID: 8a6fa691283
Revises: 4c72f48d4b6f
Create Date: 2015-11-04 06:08:39.695510

"""

# revision identifiers, used by Alembic.
revision = '8a6fa691283'
down_revision = '4c72f48d4b6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TranslationSyncLogs', sa.Column('cached', sa.Boolean(), nullable=True))
    op.add_column('TranslationSyncLogs', sa.Column('single_url', sa.Unicode(length=255), nullable=True))
    op.add_column('TranslationSyncLogs', sa.Column('source', sa.Unicode(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TranslationSyncLogs', 'source')
    op.drop_column('TranslationSyncLogs', 'single_url')
    op.drop_column('TranslationSyncLogs', 'cached')
    ### end Alembic commands ###
