"""Move collaborators to Redis

Revision ID: 9aea6784a701
Revises: 7fb89edaa44d
Create Date: 2019-01-02 11:04:38.723364

"""

# revision identifiers, used by Alembic.
revision = '9aea6784a701'
down_revision = '7fb89edaa44d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TranslationCurrentActiveUsers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TranslationCurrentActiveUsers',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('bundle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_check', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], [u'TranslationBundles.id'], name=u'TranslationCurrentActiveUsers_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'GoLabOAuthUsers.id'], name=u'TranslationCurrentActiveUsers_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
