"""Add failing tables

Revision ID: a3997837668c
Revises: dfc939482d8d
Create Date: 2017-10-15 15:03:08.130965

"""

# revision identifiers, used by Alembic.
revision = 'a3997837668c'
down_revision = 'dfc939482d8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RepositoryAppCheckUrls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_app_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Unicode(length=1024), nullable=False),
    sa.Column('url_hash', sa.Unicode(length=255), nullable=False),
    sa.Column('supports_ssl', sa.Boolean(), nullable=True),
    sa.Column('working', sa.Boolean(), nullable=True),
    sa.Column('contains_flash', sa.Boolean(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_app_id'], ['RepositoryApps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_app_id', 'url_hash')
    )
    op.create_index(op.f('ix_RepositoryAppCheckUrls_contains_flash'), 'RepositoryAppCheckUrls', ['contains_flash'], unique=False)
    op.create_index(op.f('ix_RepositoryAppCheckUrls_last_update'), 'RepositoryAppCheckUrls', ['last_update'], unique=False)
    op.create_index(op.f('ix_RepositoryAppCheckUrls_supports_ssl'), 'RepositoryAppCheckUrls', ['supports_ssl'], unique=False)
    op.create_index(op.f('ix_RepositoryAppCheckUrls_url_hash'), 'RepositoryAppCheckUrls', ['url_hash'], unique=False)
    op.create_index('ix_RepositoryAppCheckUrls_url_shortened', 'RepositoryAppCheckUrls', ['url'], unique=False, mysql_length={'url': 255})
    op.create_index(op.f('ix_RepositoryAppCheckUrls_working'), 'RepositoryAppCheckUrls', ['working'], unique=False)
    op.create_table('RepositoryAppFailures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_app_check_url_id', sa.Integer(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repository_app_check_url_id'], ['RepositoryAppCheckUrls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RepositoryAppFailures_current'), 'RepositoryAppFailures', ['current'], unique=False)
    op.create_index(op.f('ix_RepositoryAppFailures_ended'), 'RepositoryAppFailures', ['ended'], unique=False)
    op.create_index(op.f('ix_RepositoryAppFailures_started'), 'RepositoryAppFailures', ['started'], unique=False)
    op.add_column(u'RepositoryApps', sa.Column('contains_flash', sa.Boolean(), nullable=True))
    op.add_column(u'RepositoryApps', sa.Column('supports_ssl', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_RepositoryApps_contains_flash'), 'RepositoryApps', ['contains_flash'], unique=False)
    op.create_index(op.f('ix_RepositoryApps_supports_ssl'), 'RepositoryApps', ['supports_ssl'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RepositoryApps_supports_ssl'), table_name='RepositoryApps')
    op.drop_index(op.f('ix_RepositoryApps_contains_flash'), table_name='RepositoryApps')
    op.drop_column(u'RepositoryApps', 'supports_ssl')
    op.drop_column(u'RepositoryApps', 'contains_flash')
    op.drop_index(op.f('ix_RepositoryAppFailures_started'), table_name='RepositoryAppFailures')
    op.drop_index(op.f('ix_RepositoryAppFailures_ended'), table_name='RepositoryAppFailures')
    op.drop_index(op.f('ix_RepositoryAppFailures_current'), table_name='RepositoryAppFailures')
    op.drop_table('RepositoryAppFailures')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_working'), table_name='RepositoryAppCheckUrls')
    op.drop_index('ix_RepositoryAppCheckUrls_url_shortened', table_name='RepositoryAppCheckUrls')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_url_hash'), table_name='RepositoryAppCheckUrls')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_supports_ssl'), table_name='RepositoryAppCheckUrls')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_last_update'), table_name='RepositoryAppCheckUrls')
    op.drop_index(op.f('ix_RepositoryAppCheckUrls_contains_flash'), table_name='RepositoryAppCheckUrls')
    op.drop_table('RepositoryAppCheckUrls')
    # ### end Alembic commands ###
