"""Add preview_link

Revision ID: a3fbffab4a7d
Revises: def46e09c9ef
Create Date: 2018-01-15 01:31:43.138707

"""

# revision identifiers, used by Alembic.
revision = 'a3fbffab4a7d'
down_revision = 'def46e09c9ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('preview_link', sa.Unicode(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RepositoryApps', 'preview_link')
    # ### end Alembic commands ###
