"""Add app_format to RepositoryApp

Revision ID: af0f4b8caa2a
Revises: d5126053d47e
Create Date: 2019-02-20 15:02:59.298016

"""

# revision identifiers, used by Alembic.
revision = 'af0f4b8caa2a'
down_revision = 'd5126053d47e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('app_format', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RepositoryApps', 'app_format')
    # ### end Alembic commands ###
