"""Add last_download_change

Revision ID: b100c13976f
Revises: 515f518eff57
Create Date: 2017-07-25 16:35:50.640994

"""

# revision identifiers, used by Alembic.
revision = 'b100c13976f'
down_revision = '515f518eff57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RepositoryApps', sa.Column('last_download_change', sa.DateTime(), nullable=True))
    op.create_index(u'ix_RepositoryApps_last_download_change', 'RepositoryApps', ['last_download_change'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_RepositoryApps_last_download_change', table_name='RepositoryApps')
    op.drop_column('RepositoryApps', 'last_download_change')
    ### end Alembic commands ###
