"""add more indexes

Revision ID: b262149925a7
Revises: 92235b77ea53
Create Date: 2017-10-14 15:37:56.451984

"""

# revision identifiers, used by Alembic.
revision = 'b262149925a7'
down_revision = '92235b77ea53'

from collections import defaultdict

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

from appcomposer.db import db
from appcomposer.application import app

metadata = db.MetaData()
ActiveTranslationMessage = db.Table('ActiveTranslationMessages', metadata,
    sa.Column('id', sa.Integer, nullable=True),
    sa.Column('key', sa.Unicode(length=255), nullable=True),
    sa.Column('bundle_id', sa.Integer, nullable=False),
)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with app.app_context():
        duplicated_active_messages = list(db.session.query(ActiveTranslationMessage.c.key, ActiveTranslationMessage.c.bundle_id).group_by(ActiveTranslationMessage.c.bundle_id, ActiveTranslationMessage.c.key).having(func.count(ActiveTranslationMessage.c.id) > 1).all())
        keys = [ k for k, b in duplicated_active_messages ]
        bundle_ids = [ b for k, b in duplicated_active_messages ]

        all_results = defaultdict(list)
        for atm in db.session.query(ActiveTranslationMessage).filter(ActiveTranslationMessage.c.key.in_(keys), ActiveTranslationMessage.c.bundle_id.in_(bundle_ids)).all():
            all_results[atm.key, atm.bundle_id].append(atm)

        all_ids = []
        for key, bundle_id in duplicated_active_messages:
            for atm in all_results[key, bundle_id][1:]:
                all_ids.append(atm.id)

    delete_stmt = ActiveTranslationMessage.delete(ActiveTranslationMessage.c.id.in_(all_ids))
    connection = op.get_bind()
    connection.execute(delete_stmt)

    op.create_unique_constraint(None, 'ActiveTranslationMessages', ['bundle_id', 'key'])
    op.create_unique_constraint(None, 'RepositoryApp2languages', ['repository_app_id', 'language_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'RepositoryApp2languages', type_='unique')
    op.drop_constraint(None, 'ActiveTranslationMessages', type_='unique')
    # ### end Alembic commands ###
