"""Add applications translations

Revision ID: df42ba6d96
Revises: 4811ae4298e3
Create Date: 2015-07-31 15:15:05.822909

"""

# revision identifiers, used by Alembic.
revision = 'df42ba6d96'
down_revision = '4811ae4298e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmbedApplicationTranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embed_application_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Unicode(length=255), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=False),
    sa.ForeignKeyConstraint(['embed_application_id'], ['EmbedApplications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_EmbedApplicationTranslation_language', 'EmbedApplicationTranslation', ['language'], unique=False)
    op.create_index(u'ix_EmbedApplicationTranslation_url', 'EmbedApplicationTranslation', ['url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_EmbedApplicationTranslation_url', table_name='EmbedApplicationTranslation')
    op.drop_index(u'ix_EmbedApplicationTranslation_language', table_name='EmbedApplicationTranslation')
    op.drop_table('EmbedApplicationTranslation')
    ### end Alembic commands ###
