// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.golab = window.golab || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools.configurationDefinition = window.golab.tools.configurationDefinition || {};

  window.golab.tools.configurationDefinition["conceptmapper"] = {
    debug: {
      label: "Debug mode?",
      description: "Turns on/off verbose console messages.",
      type: "boolean",
      value: {{ debug }},
      configurable: "true"
    },
    auto_load: {
      label: "Auto load?",
      description: "Automatically load the latest saved file?",
      type: "boolean",
      value: {{ auto_load }},
      configurable: "true"
    },
    actionlogging: {
      label: "actionlogging",
      description: "Configures the action logging target.",
      type: "string",
      value: {{ actionlogging }},
      configurable: "true"
    },
    show_prompts: {
      label: "Show prompts?",
      description: "Are incoming prompts and notifications shown as a pop-up message?",
      type: "boolean",
      value: {{ show_prompts }},
      configurable: "true"
    },
    textarea_concepts: {
      label: "Show text input?",
      description: "Is the user allowed to freely create and edit new concepts?",
      type: "boolean",
      value: {{ textarea_concepts }},
      configurable: "true"
    },
    combobox_concepts: {
      label: "Show combobox input?",
      description: "Is the combobox node with pre-defined concepts available?",
      type: "boolean",
      value: {{ combobox_concepts}},
      configurable: "true"
    },
    drop_external: {
      label: "Drag'n'drop external concepts?",
      description: "Is it possible to drag highlighted text as new concepts from other applications?",
      type: "boolean",
      value: {{ drop_external }},
      configurable: "true"
    },
    concepts: {
      label: "Available concepts",
      description: "A list with pre-defined concepts to select from in the combobox.",
      type: "array",
      value: {{concepts}},
      configurable: "true"
    },
    relations: {
      label: "Available relations",
      description: "A list with pre-defined relations to select from.",
      type: "array",
      value: {{ relations }},
      configurable: "true"
    }
  };

}).call(this);

/*
//@ sourceMappingURL=configuration_definition.map
*/
