// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.golab = window.golab || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools = window.golab.tools || {};

  window.golab.tools.configuration = window.golab.tools.configuration || {};

  window.golab.tools.configuration["conceptmapper"] = {
    debug: {
      type: "boolean",
      value: {{ debug }}
    },
    auto_load: {
      type: "boolean",
      value: {{ auto_load }}
    },
    actionlogging: {
      type: "string",
      value: {{ actionlogging }}
    },
    show_prompts: {
      type: "boolean",
      value: {{ show_prompts }}
    },
    textarea_concepts: {
      type: "boolean",
      value: {{ textarea_concepts }}
    },
    combobox_concepts: {
      type: "boolean",
      value: {{ combobox_concepts}}
    },
    drop_external: {
      type: "boolean",
      value: {{ drop_external }}
    },
    concepts: {
      type: "array",
      value: {{concepts}}
    },
    relations: {
      type: "array",
      value: {{ relations }}
    }
  };

}).call(this);

/*
//@ sourceMappingURL=configuration_default.map
*/
