// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  window.ut = window.ut || {};

  ut.tools = ut.tools || {};

  ut.tools.hypothesis = ut.tools.hypothesis || {};

  ut.tools.hypothesis.HypothesisApp.controller("DefaultTemplates", function($scope) {
    return $scope.templates = {{ domain }}
  });

}).call(this);

/*
//@ sourceMappingURL=BuoyancyTemplates.map
*/
